name: CI/CD for Nginx

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Nginx Configuration
        run: docker run --rm -v ${{ github.workspace }}/nginx:/etc/nginx:ro nginx:alpine nginx -t -c /etc/nginx/nginx.conf

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Nginx Configuration
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sshpass
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r nginx/* user@yourserver:/etc/nginx/
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no user@yourserver 'sudo systemctl reload nginx'
